name: Context

on:
  push:
    branches: main

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: "Step-1: GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT
