name: simple Js Hello world

on:
  push:
    branches:
      - main
      - "feat/*"
    tags:
      - v1*
    paths:
      - "*.js"
      - "*.ts"
  pull_request:
    branches:
      - master
      - "!feat/a" # exclude this branch
    # branches-ignore:
    #   - main
    paths-ignore:
      - "docs/*"

jobs:
  js-action:
    runs-on: ubuntu-latest
    steps:
      - name: use my repository
        uses: actions/checkout@v4
      - name: commands
        run: |
          ip addr
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
