name: simple Js Hello world

on:
  schedule:
    - cron: "* * * * *"

jobs:
  js-action:
    runs-on: ubuntu-latest
    steps:
      - name: use my repository
        uses: actions/checkout@v4
      - name: commands
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
s