name: Matrix

on:
  push:
    branches:
      - main

jobs:
  node-version:
    strategy:
      matrix:
        node_version: [10, 11]
    runs-on: ubuntu-latest
    steps:
      - name: "step-1: node-version"
        run: node --version
      - name: "step-2: set up node"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - name: "step-3: node-verion"
        run: node --version
