name: Shell commands

on: [pull_request]

jobs: # is object
  run-command: # object
    runs-on: ubuntu-latest
    steps: # steps is array of objects
      - name: echo string
        run: echo 'hello!!'
      - name: mutli line commands
        run: |
          node -v
          npm -v
      - name: run python command
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-windows:
    runs-on: windows-latest
    needs: [run-command]
    steps:
      - name: command on powershell
        run: Get-Location
      - name: command on bash
        run: pwd
        shell: bash
