name: Shell commands

on: [push]

jobs: # is object
  run-command: # object
    runs-on: ubuntu-latest
    steps: # steps is array of objects
      - name: echo string
        run: echo 'hello!!'
      - name: mutli line commands
        run: |
          node -v
          npm -v
      - name: run python command
        run: |
          import platform
          print(platform.processor())
        shell: python
